image: offscale/golang-builder-alpine3.8

stages:
  - test
  - build
  
before_script:
    - mkdir -p /go/src/github.com/SamuelMarks/
    - cp -r /mirrors/lachesis /go/src/github.com/SamuelMarks/lachesis
    - ls /go/src/github.com/SamuelMarks/
    - ls /go/src/github.com/SamuelMarks/lachesis
    - go get -v github.com/SamuelMarks/batch-ethkey
    - go get -u -d github.com/magefile/mage
    - cd /go/src/github.com/SamuelMarks/lachesis
    - ln -s /go/src/github.com/SamuelMarks /go/src/github.com/andrecronje
    - glide install
    
test code:
  stage: test
  allow_failure: true
  script:
    - cd /go/src/github.com/SamuelMarks/lachesis
    - make test
    
build code:
  stage: build
  script:
    - cd /go/src/github.com/SamuelMarks/lachesis/scripts
    - ./multi_build.bash