image: offscale/golang-builder-alpine3.8

stages:
  - test
  - build
  - deploy

before_script:
  - cd /home/gitlab-runner/go/src/github.com/SamuelMarks/lachesis
  
test code:
  stage: test
  allow_failure: true
  script:
    - make test

build lachesis:
  stage: build
  script: 
    - go get -v github.com/SamuelMarks/batch-ethkey && go get -u -d github.com/magefile/mage && glide i && ./scripts/multi_build.bash

deploy lachesis:
  stage: deploy
  script: timeout 5m logshold=-1,-1,-1,4,0,0 ./scripts/multi_run.bash
