image: offscale/golang-builder-alpine3.8

stages:
  - test
  - build
  - deploy
  
test code:
  stage: test
  allow_failure: true
  script:
    - mkdir -p /go/src/github.com/SamuelMarks/
    - mv /mirrors/lachesis /go/src/github.com/SamuelMarks/
    - go get -v github.com/SamuelMarks/batch-ethkey
    - go get -u -d github.com/magefile/mage 
    - glide i
