image: golang:1.11.1-stretch

stages:
  - test
  - build
  - deploy

# Jobs Section
# Below are jobs. Jobs are executed in parallel during the matching stage.

# Note that the script is just bash, so if you use a Makefile, you could run
# `make test`, etc. Also note that you can
test code:
  stage: test
  script:
    - echo "Placeholder for test command"
    - echo "No, really, just a placeholder"

build lachesis:
  stage: build
  script: ./scripts/multi_build.bash

deploy lachesis:
  stage: deploy
  script: timeout 5m logshold=-1,-1,-1,4,0,0 ./scripts/multi_run.bash
