language: go

go:
- "1.11.x"

go_import_path: github.com/andrecronje/lachesis

cache:
  directories:
  - "$HOME/.glide/cache"
  - "$TRAVIS_BUILD_DIR/vendor"

before_install:
- curl https://glide.sh/get | sh
- go get -v github.com/SamuelMarks/batch-ethkey
- go get -u -d github.com/magefile/mage
- pushd "$GOPATH/src/github.com/magefile/mage" && go run bootstrap.go && popd
- if ! find vendor -mindepth 1 2>/dev/null | read; then make vendor; fi

addons:
  apt:
    packages:
    - jq

jobs:
  include:
  - stage: test
    script: make test
  - stage: testnet
    script: env && scripts/multi.bash
    env: n=3 logshold='-1,-1,-1,5,0,0' entry='main' BUILD_DIR="$TRAVIS_BUILD_DIR"
