language: go

go:
- "1.11.x"

go_import_path: github.com/andrecronje/lachesis

before_install:
- curl https://glide.sh/get | sh
- go get -v github.com/SamuelMarks/batch-ethkey
- go get -u -d github.com/magefile/mage
- pushd $GOPATH/src/github.com/magefile/mage && go run bootstrap.go && popd
- make vendor

addons:
  apt:
    packages:
    - jq

jobs:
  include:
  - stage: test
    script: echo "$PWD" && ls -al && make test
  - stage: build
    script: make build
  - stage: deploy
    script: env && scripts/multi.bash
    env: n=3 logshold='-1,-1,-1,5,0,0' entry='main' BUILD_DIR='/home/travis/gopath/src/github.com/andrecronje/lachesis'
