// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package poset

import (
	fmt "fmt"
	peers "github.com/Fantom-foundation/go-lachesis/src/peers"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransactionType int32

const (
	TransactionType_PEER_ADD    TransactionType = 0
	TransactionType_PEER_REMOVE TransactionType = 1
)

var TransactionType_name = map[int32]string{
	0: "PEER_ADD",
	1: "PEER_REMOVE",
}

var TransactionType_value = map[string]int32{
	"PEER_ADD":    0,
	"PEER_REMOVE": 1,
}

func (x TransactionType) String() string {
	return proto.EnumName(TransactionType_name, int32(x))
}

func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

type InternalTransaction struct {
	Type                 TransactionType `protobuf:"varint,1,opt,name=Type,proto3,enum=poset.TransactionType" json:"Type,omitempty"`
	Peer                 *peers.Peer     `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *InternalTransaction) Reset()         { *m = InternalTransaction{} }
func (m *InternalTransaction) String() string { return proto.CompactTextString(m) }
func (*InternalTransaction) ProtoMessage()    {}
func (*InternalTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *InternalTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalTransaction.Unmarshal(m, b)
}
func (m *InternalTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalTransaction.Marshal(b, m, deterministic)
}
func (m *InternalTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalTransaction.Merge(m, src)
}
func (m *InternalTransaction) XXX_Size() int {
	return xxx_messageInfo_InternalTransaction.Size(m)
}
func (m *InternalTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_InternalTransaction proto.InternalMessageInfo

func (m *InternalTransaction) GetType() TransactionType {
	if m != nil {
		return m.Type
	}
	return TransactionType_PEER_ADD
}

func (m *InternalTransaction) GetPeer() *peers.Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

type BlockSignature struct {
	Validator            []byte   `protobuf:"bytes,1,opt,name=Validator,proto3" json:"Validator,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=Index,proto3" json:"Index,omitempty"`
	Signature            string   `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockSignature) Reset()         { *m = BlockSignature{} }
func (m *BlockSignature) String() string { return proto.CompactTextString(m) }
func (*BlockSignature) ProtoMessage()    {}
func (*BlockSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *BlockSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockSignature.Unmarshal(m, b)
}
func (m *BlockSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockSignature.Marshal(b, m, deterministic)
}
func (m *BlockSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockSignature.Merge(m, src)
}
func (m *BlockSignature) XXX_Size() int {
	return xxx_messageInfo_BlockSignature.Size(m)
}
func (m *BlockSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockSignature.DiscardUnknown(m)
}

var xxx_messageInfo_BlockSignature proto.InternalMessageInfo

func (m *BlockSignature) GetValidator() []byte {
	if m != nil {
		return m.Validator
	}
	return nil
}

func (m *BlockSignature) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *BlockSignature) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type EventBody struct {
	Transactions         [][]byte               `protobuf:"bytes,1,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	InternalTransactions []*InternalTransaction `protobuf:"bytes,2,rep,name=InternalTransactions,proto3" json:"InternalTransactions,omitempty"`
	Parents              []string               `protobuf:"bytes,3,rep,name=Parents,proto3" json:"Parents,omitempty"`
	Creator              []byte                 `protobuf:"bytes,4,opt,name=Creator,proto3" json:"Creator,omitempty"`
	Index                int64                  `protobuf:"varint,5,opt,name=Index,proto3" json:"Index,omitempty"`
	BlockSignatures      []*BlockSignature      `protobuf:"bytes,6,rep,name=BlockSignatures,proto3" json:"BlockSignatures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EventBody) Reset()         { *m = EventBody{} }
func (m *EventBody) String() string { return proto.CompactTextString(m) }
func (*EventBody) ProtoMessage()    {}
func (*EventBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *EventBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventBody.Unmarshal(m, b)
}
func (m *EventBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventBody.Marshal(b, m, deterministic)
}
func (m *EventBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBody.Merge(m, src)
}
func (m *EventBody) XXX_Size() int {
	return xxx_messageInfo_EventBody.Size(m)
}
func (m *EventBody) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBody.DiscardUnknown(m)
}

var xxx_messageInfo_EventBody proto.InternalMessageInfo

func (m *EventBody) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *EventBody) GetInternalTransactions() []*InternalTransaction {
	if m != nil {
		return m.InternalTransactions
	}
	return nil
}

func (m *EventBody) GetParents() []string {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *EventBody) GetCreator() []byte {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *EventBody) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *EventBody) GetBlockSignatures() []*BlockSignature {
	if m != nil {
		return m.BlockSignatures
	}
	return nil
}

type EventMessage struct {
	Body                  *EventBody `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
	Signature             string     `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	FlagTable             []byte     `protobuf:"bytes,3,opt,name=FlagTable,proto3" json:"FlagTable,omitempty"`
	WitnessProof          []string   `protobuf:"bytes,4,rep,name=WitnessProof,proto3" json:"WitnessProof,omitempty"`
	SelfParentIndex       int64      `protobuf:"varint,5,opt,name=SelfParentIndex,proto3" json:"SelfParentIndex,omitempty"`
	OtherParentCreatorIDs []int64    `protobuf:"varint,6,rep,packed,name=OtherParentCreatorIDs,proto3" json:"OtherParentCreatorIDs,omitempty"`
	OtherParentIndexes    []int64    `protobuf:"varint,7,rep,packed,name=OtherParentIndexes,proto3" json:"OtherParentIndexes,omitempty"`
	CreatorID             int64      `protobuf:"varint,8,opt,name=CreatorID,proto3" json:"CreatorID,omitempty"`
	TopologicalIndex      int64      `protobuf:"varint,9,opt,name=TopologicalIndex,proto3" json:"TopologicalIndex,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}   `json:"-"`
	XXX_unrecognized      []byte     `json:"-"`
	XXX_sizecache         int32      `json:"-"`
}

func (m *EventMessage) Reset()         { *m = EventMessage{} }
func (m *EventMessage) String() string { return proto.CompactTextString(m) }
func (*EventMessage) ProtoMessage()    {}
func (*EventMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{3}
}

func (m *EventMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventMessage.Unmarshal(m, b)
}
func (m *EventMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventMessage.Marshal(b, m, deterministic)
}
func (m *EventMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMessage.Merge(m, src)
}
func (m *EventMessage) XXX_Size() int {
	return xxx_messageInfo_EventMessage.Size(m)
}
func (m *EventMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EventMessage proto.InternalMessageInfo

func (m *EventMessage) GetBody() *EventBody {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *EventMessage) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *EventMessage) GetFlagTable() []byte {
	if m != nil {
		return m.FlagTable
	}
	return nil
}

func (m *EventMessage) GetWitnessProof() []string {
	if m != nil {
		return m.WitnessProof
	}
	return nil
}

func (m *EventMessage) GetSelfParentIndex() int64 {
	if m != nil {
		return m.SelfParentIndex
	}
	return 0
}

func (m *EventMessage) GetOtherParentCreatorIDs() []int64 {
	if m != nil {
		return m.OtherParentCreatorIDs
	}
	return nil
}

func (m *EventMessage) GetOtherParentIndexes() []int64 {
	if m != nil {
		return m.OtherParentIndexes
	}
	return nil
}

func (m *EventMessage) GetCreatorID() int64 {
	if m != nil {
		return m.CreatorID
	}
	return 0
}

func (m *EventMessage) GetTopologicalIndex() int64 {
	if m != nil {
		return m.TopologicalIndex
	}
	return 0
}

func init() {
	proto.RegisterEnum("poset.TransactionType", TransactionType_name, TransactionType_value)
	proto.RegisterType((*InternalTransaction)(nil), "poset.InternalTransaction")
	proto.RegisterType((*BlockSignature)(nil), "poset.BlockSignature")
	proto.RegisterType((*EventBody)(nil), "poset.EventBody")
	proto.RegisterType((*EventMessage)(nil), "poset.EventMessage")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xdf, 0x6a, 0xdb, 0x4c,
	0x10, 0xc5, 0x3f, 0x59, 0x76, 0x12, 0x8f, 0x44, 0x6c, 0xf6, 0x4b, 0xca, 0x12, 0x0a, 0x15, 0xa6,
	0x17, 0xc2, 0x10, 0xb9, 0xb8, 0xbd, 0x2d, 0xa5, 0xa9, 0x1d, 0xf0, 0x45, 0x1a, 0xb3, 0x31, 0xe9,
	0x65, 0x59, 0xcb, 0x63, 0x59, 0x54, 0xd9, 0x35, 0xbb, 0xeb, 0xd2, 0xbc, 0x42, 0x1f, 0xb6, 0xcf,
	0x50, 0x34, 0x72, 0xfc, 0xaf, 0xbe, 0x11, 0xcc, 0x39, 0x33, 0xb3, 0x73, 0x7e, 0x20, 0x08, 0xf0,
	0x27, 0x2a, 0x97, 0x2c, 0x8d, 0x76, 0x9a, 0x35, 0x96, 0xda, 0xa2, 0xbb, 0xfa, 0x98, 0xe5, 0x6e,
	0xb1, 0x9a, 0x26, 0xa9, 0x7e, 0xea, 0xdd, 0x4a, 0xe5, 0xf4, 0xd3, 0xf5, 0x5c, 0xaf, 0xd4, 0x4c,
	0xba, 0x5c, 0xab, 0x5e, 0xa6, 0xaf, 0x0b, 0x99, 0x2e, 0xd0, 0xe6, 0xb6, 0x67, 0x4d, 0xda, 0x5b,
	0x22, 0x1a, 0x4b, 0xdf, 0x6a, 0x4b, 0x67, 0x0a, 0xff, 0x8f, 0x94, 0x43, 0xa3, 0x64, 0x31, 0x31,
	0x52, 0x59, 0x99, 0x96, 0x73, 0xac, 0x0b, 0xf5, 0xc9, 0xf3, 0x12, 0xb9, 0x17, 0x79, 0xf1, 0x79,
	0xff, 0x55, 0x42, 0x6f, 0x25, 0x3b, 0x1d, 0xa5, 0x2b, 0xa8, 0x87, 0xbd, 0x81, 0x7a, 0xb9, 0x90,
	0xd7, 0x22, 0x2f, 0x0e, 0xfa, 0x41, 0x42, 0x6f, 0x24, 0x63, 0x44, 0x23, 0xc8, 0xe8, 0x4c, 0xe1,
	0xfc, 0xa6, 0xd0, 0xe9, 0x8f, 0x87, 0x3c, 0x53, 0xd2, 0xad, 0x0c, 0xb2, 0xd7, 0xd0, 0x7c, 0x94,
	0x45, 0x3e, 0x93, 0x4e, 0x1b, 0x7a, 0x23, 0x14, 0x5b, 0x81, 0x5d, 0x40, 0x63, 0xa4, 0x66, 0xf8,
	0x8b, 0x36, 0xfa, 0xa2, 0x2a, 0xca, 0x99, 0xcd, 0x02, 0xee, 0x47, 0x5e, 0xdc, 0x14, 0x5b, 0xa1,
	0xf3, 0xbb, 0x06, 0xcd, 0x61, 0x49, 0xe7, 0x46, 0xcf, 0x9e, 0x59, 0x07, 0xc2, 0x9d, 0x5b, 0x2d,
	0xf7, 0x22, 0x3f, 0x0e, 0xc5, 0x9e, 0xc6, 0xbe, 0xc2, 0xc5, 0x91, 0xe4, 0x96, 0xd7, 0x22, 0x3f,
	0x0e, 0xfa, 0x57, 0xeb, 0xc8, 0x47, 0x5a, 0xc4, 0xd1, 0x39, 0xc6, 0xe1, 0x74, 0x2c, 0x0d, 0x2a,
	0x67, 0xb9, 0x1f, 0xf9, 0x71, 0x53, 0xbc, 0x94, 0xa5, 0xf3, 0xc5, 0x20, 0x65, 0xad, 0x53, 0xd6,
	0x97, 0x72, 0x9b, 0xb4, 0xb1, 0x9b, 0xf4, 0x13, 0xb4, 0xf6, 0x79, 0x59, 0x7e, 0x42, 0x47, 0x5d,
	0xae, 0x8f, 0xda, 0x77, 0xc5, 0x61, 0x77, 0xe7, 0x4f, 0x0d, 0x42, 0x82, 0x71, 0x87, 0xd6, 0xca,
	0x0c, 0xd9, 0x5b, 0xa8, 0x97, 0x5c, 0x08, 0x75, 0xd0, 0x6f, 0xaf, 0xd7, 0x6c, 0x78, 0x09, 0x72,
	0xf7, 0x09, 0xd7, 0x0e, 0x08, 0x97, 0xee, 0x6d, 0x21, 0xb3, 0x89, 0x9c, 0x16, 0x15, 0xff, 0x50,
	0x6c, 0x85, 0x92, 0xf8, 0xb7, 0xdc, 0x29, 0xb4, 0x76, 0x6c, 0xb4, 0x9e, 0xf3, 0x3a, 0x21, 0xd8,
	0xd3, 0x58, 0x0c, 0xad, 0x07, 0x2c, 0xe6, 0x15, 0x96, 0xdd, 0xdc, 0x87, 0x32, 0xfb, 0x00, 0x97,
	0xf7, 0x6e, 0x81, 0xa6, 0xd2, 0xd6, 0xb4, 0x46, 0x83, 0x8a, 0x83, 0x2f, 0x8e, 0x9b, 0x2c, 0x01,
	0xb6, 0x63, 0xd0, 0x26, 0xb4, 0xfc, 0x94, 0x46, 0x8e, 0x38, 0x65, 0xa2, 0xcd, 0x34, 0x3f, 0xa3,
	0x4b, 0xb6, 0x02, 0xeb, 0x42, 0x7b, 0xa2, 0x97, 0xba, 0xd0, 0x59, 0x9e, 0xca, 0xa2, 0x3a, 0xb7,
	0x49, 0x4d, 0xff, 0xe8, 0xdd, 0x77, 0xd0, 0x3a, 0xf8, 0x37, 0x58, 0x08, 0x67, 0xe3, 0xe1, 0x50,
	0x7c, 0xff, 0x3c, 0x18, 0xb4, 0xff, 0x63, 0x2d, 0x08, 0xa8, 0x12, 0xc3, 0xbb, 0xfb, 0xc7, 0x61,
	0xdb, 0x9b, 0x9e, 0xd0, 0xef, 0xf7, 0xfe, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x26, 0xbf,
	0xf8, 0xd3, 0x03, 0x00, 0x00,
}
